### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by jacob085** [sscheetz/etsy-python2#3]
Hi there. 
Thanks for your work, very helpful 
I am learning python (very very basic skills).
I try to use the OAuth Helper to get the token 
Seems like everything works good, but once i allow the app to access my data i am not redirect to the page for the verification code... so i can't terminate the OAuth process.

do you have any suggestions?

thanks
v.

**Comment by sscheetz** [comment]
What happens when you tell etsy you approve access? Do you get redirected to a 404 page or something like that? If so, that is happening because are you passing a callback_uri to get_request_url_and_token_secret that doesnt exist (your webserver isn't exposing the url as an endpoint).

Unfortunately this library doesn't support manually inputting the verification code at this time. Generally, applications will pass a url for the callback_uri that is owned by their webserver and when the user clicks approve on Etsy's page, Etsy then redirects the user back to your app via the callback_url. You are probably redirecting to a url for and endpoint that currently doesnt exist.

I can add a quick enhancement this weekend that lets you manually enter the callback_uri, but if you just want your oauth tokens to start making requests you can work around this with something like

```python
    auth_callback_url = 'https://fakecallback.com'
    permission_scopes = ['transactions_r', 'listings_r']
    login_url, temp_oauth_token_secret = EtsyOAuthHelper.get_request_url_and_token_secret(api_key, shared_secret, permission_scopes, auth_callback_url)
    print(login_url)
    # manually navigate to the login_url and tell etsy you approve
    # get redirect to fakecallback.com and copy and paste the url into the console
    # the next line of code will parse the url you pasted and get the verification code out of it
    oauth_token, oauth_token_secret = EtsyOAuthHelper.get_oauth_token(api_key, shared_secret, temp_oauth_token_secret, input('paste: '))
    print(oauth_token) # your access_token
    print(oauth_token_secret) # your access_token_secret

**Comment by sscheetz** [comment]
I added a method that allows you to manually input the verification code instead of using a callback url so update your package to version 0.6.0 and refer to "Obtaining Etsy OAuthCredentials" in the readme.

Specifically if you want to be redirected to the page showing the verification code, don't pass a callback_url

e.g.
login_url, temp_oauth_token_secret = EtsyOAuthHelper.get_request_url_and_token_secret(api_key, shared_secret, permission_scopes)

but there are some other things you need to do to finish the process so refer to the readme.

**Comment by jacob085** [comment]
Hi Sean

Thanks so much
i will try this night

thanks again

v.

**Comment by jacob085** [comment]
It works!!!
thanks a lot!!

v.
