### ISSUE TITLE
Unable to fetch transactions using listing_id

### ISSUE THREAD

**Issue by fra988w** [sscheetz/etsy-python2#8]
Hi there,

Firstly, this is a great piece of kit and I can see myself using it extensively, so thank you!

The issue I'm having is that listing transaction data cannot be retrieved using listing_id.  I've successfully set up oath with transactions_r set within permission scope and tested with a number of different listing IDs which I know to be correct.

For example... https://www.etsy.com/listing/763077740

If I'm correctly using this API endpoint, the list of transactions associated with this listings should be retrievable using:
`etsy.findAllListingTransactions(listing_id=763077740)`

However the following error is returned:
`ValueError: Could not decode response from Etsy as JSON: status_code: 404, text: 'Listing not found for listing_id: 763077740', url 'https://openapi.etsy.com/v2/listings/763077740/transactions'`

Any help would be greatly appreciated!

**Comment by fra988w** [comment]
Never mind, I see now the sales figure listed on-site is the seller's total, not the item total.

**Comment by sscheetz** [comment]
Sorry missed this. Need to find a way to get text notifications or something.

Don't quite understand. Seems like you were trying to find the total sales for a certain item by getting all transactions and summing them, then looked at the seller's total instead of the per item total. Your way should have worked, but maybe im misunderstanding what's going on. Would be interested in knowing if the findAllListingTransactions method is working. I'll test after work myself, but curious about your experience as well.
